steps:
  - name: gcr.io/cloud-builders/gcloud
    id: "Build: meta cloud-builder"
    waitFor:
      - "-"
    args:
      - beta
      - builds
      - triggers
      - import
      - --source=.cicd/triggers/meta-cloud-builder.trigger.yaml
  - name: gcr.io/cloud-builders/gcloud
    id: "Apply: meta triggers"
    waitFor:
      - "-"
    args:
      - beta
      - builds
      - triggers
      - import
      - --source=.cicd/triggers/meta-trigger.trigger.yaml
  - name: gcr.io/cloud-builders/gcloud
    id: "Build: meta triggers builder"
    waitFor:
      - "-"
    args:
      - beta
      - builds
      - triggers
      - import
      - --source=.cicd/triggers/meta-triggers.trigger.yaml
