steps:
  - name: gcr.io/$PROJECT_ID/meta-cloud-builder
    id: "Build: custom images asynchronously"
    waitFor:
      - "-"
    args:
      - .cicd/builders/custom-builders.yaml
      - --timeout=900
      - --async
tags: ["cloud-builders"]
