steps:
  - name: gcr.io/$PROJECT_ID/cancelot
    id: "Cancelot"
    args:
      - "--current_build_id"
      - "$BUILD_ID"
      - "--branch_name"
      - "$BRANCH_NAME"
      - "--same_trigger_only"
  - name: gcr.io/$PROJECT_ID/shellcheck
    id: "Shellcheck"
    waitFor:
      - "Cancelot"
    args:
      - "**/*.sh"
tags: ["lint"]
