tags:
  - "cloud-builders-community"

steps:
  - name: gcr.io/cloud-builders/docker
    id: "Build: meta builder image"
    waitFor:
      - "-"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/meta-cloud-builder"
      - "meta-cloud-builder"
images:
  - gcr.io/$PROJECT_ID/meta-cloud-builder
