steps:
  - name: gcr.io/cloud-builders/docker
    id: "Build: meta builder image"
    waitFor:
      - "-"
    dir: ./meta-cloud-builder
    args: ["build", "-t", "gcr.io/$PROJECT_ID/meta-cloud-builder", "."]
  # sanity check
  - name: gcr.io/$PROJECT_ID/meta-cloud-builder
    id: "Build: custom images"
    waitFor:
      - "Build: meta builder image"
    dir: ./meta-cloud-builder
    args:
      - ./test-config.yaml
  # check if cancelot was built by the test-config.yaml
  - name: gcr.io/cloud-builders/gcloud
    id: "Validate: check final cancelot image"
    waitFor:
      - "Build: custom images"
    dir: ./meta-cloud-builder
    args:
      - container
      - images
      - list
      - --filter
      - cancelot
  - name: gcr.io/cloud-builders/gcloud
    id: "Validate: check final cache image"
    waitFor:
      - "Build: custom images"
    dir: ./meta-cloud-builder
    args:
      - container
      - images
      - list
      - --filter
      - cache
images:
  - gcr.io/$PROJECT_ID/meta-cloud-builder
tags: ["cloud-builders-community"]
